language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy

assistant_id: 20250106-123612-miniature-siamese
